### ISSUE TITLE
Top Tool Bar with File etc missing

### ISSUE THREAD

**Issue by 4302dam** [node-red/node-red-desktop#3]
Downloaded the new desktop. Love it thanks. I imported a flow and everything worked fine but there was no way to save it. The top menu tool bar is missing.

**Comment by kazuhitoyokoi** [comment]
@4302dam Hello! I think that you are using another implementation which has the same name. I found the issue which you mentioned.
https://github.com/sakazuki/node-red-desktop/issues/60

**Comment by 4302dam** [comment]
Thank you. Apologies for the confusion.
Dave

David March, CEO
Exergy Energy
Always Green, Always On, Always Save
Schedule a meeting: https://calendly.com/exergyenergy/15min
(704) 778-1909
***@***.******@***.***>
www.ExergyEnergy.com<http://www.exergyenergy.com/>
